# Generated by Django 3.1.5 on 2021-02-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210129_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
    ]
