# Generated by Django 3.1.5 on 2021-02-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_poll_send_now'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='send_now',
            new_name='start',
        ),
        migrations.AddField(
            model_name='poll',
            name='datetime_end',
            field=models.DateTimeField(null=True),
        ),
    ]
