# Generated by Django 3.1.5 on 2021-02-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_poll_datetime_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
