# Generated by Django 3.1.5 on 2021-02-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_poll_ended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_end', models.DateTimeField()),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.poll')),
            ],
        ),
    ]
