# Generated by Django 3.1.5 on 2021-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='region',
            field=models.CharField(choices=[('sibir', 'Сибирь'), ('center', 'Центр')], default='center', max_length=16),
        ),
        migrations.AddField(
            model_name='poll',
            name='region',
            field=models.CharField(choices=[('sibir', 'Сибирь'), ('center', 'Центр')], default='center', max_length=16),
        ),
    ]
