# Generated by Django 3.1.5 on 2021-02-07 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210206_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='first_answer_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
